/** @type {import('cz-git').UserConfig} */
export default {
  ignores: [commit => commit.includes('init')],
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [1, 'always'],
    'header-max-length': [2, 'always', 108],
    'subject-empty': [2, 'never'],
    'type-empty': [2, 'never'],
    'subject-case': [0],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'wip',
        'workflow',
        'types',
        'release'
      ]
    ]
  },
  prompt: {
    alias: { fd: 'docs: fix typos' },
    messages: {
      type: 'Select the type of commit you want to make:',
      scope: 'Select a scope of the commit (optional):',
      customScope: 'Enter a custom scope for the commit:',
      subject: 'Fill in a brief and concise description of the changes:\n',
      body: 'Fill in a more detailed description of the changes (optional). Use "|" to break lines:\n',
      breaking: 'List any breaking changes (optional). Use "|" to break lines:\n',
      footerPrefixesSelect: 'Select issue prefix for associated issues (optional):',
      customFooterPrefix: 'Enter a custom issue prefix:',
      footer: 'List associated issues (optional) e.g., #31, #I3244:\n',
      confirmCommit: 'Do you want to submit or modify the commit?'
    },
    types: [
      { value: 'feat', name: 'feat:    ✨  New feature | A new feature', emoji: '✨' },
      { value: 'fix', name: 'fix:    🐛  Bug fix | A bug fix', emoji: '🐛' },
      { value: 'docs', name: 'docs:    📝  Documentation only changes | Documentation only changes', emoji: '📝' },
      { value: 'style', name: 'style:    💄  Code formatting | Changes that do not affect the meaning of the code', emoji: '💄' },
      { value: 'refactor', name: 'refactor:    ♻️  Code refactoring | A code change that neither fixes a bug nor adds a feature', emoji: '♻️' },
      { value: 'perf', name: 'perf:    ⚡️  Performance improvement | A code change that improves performance', emoji: '⚡️' },
      { value: 'test', name: 'test:    ✅  Testing related | Adding missing tests or correcting existing tests', emoji: '✅' },
      { value: 'build', name: 'build:    📦️   Build related | Changes that affect the build system or external dependencies', emoji: '📦️' },
      { value: 'ci', name: 'ci:    🎡 Continuous integration | Changes to our CI configuration files and scripts', emoji: '🎡' },
      { value: 'chore', name: 'chore:    🔨  Other changes | Other changes that do not modify src or test files', emoji: '🔨' },
      { value: 'revert', name: 'revert:    ⏪️  Revert code | Revert to a commit', emoji: '⏪️' }
    ],
    useEmoji: true,
    emojiAlign: 'left',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      { value: 'link', name: 'link:     Link to ongoing ISSUES' },
      { value: 'closed', name: 'closed:   Mark ISSUES as completed' }
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: ''
  }
}
